### ISSUE TITLE
Add license to allow reuse

### ISSUE THREAD

**Issue by johanms** [shaharkadmiel/CTG_Course#1]
The ```Array``` subclass of the obspy Intentory looks very good and I would like to use it in another project, but I notice that there is no license included in the repo.

Is this intentional? If not, could you please include one?

Many thanks and best regards,
Johan Markus Steinholt

**Comment by shaharkadmiel** [comment]
Hi @johanms, this is part of a grad-school course I gave in our department at Delft University of Technology. I was supposed to take this repo down after the course but as you stumbled upon it you are more than welcome to reuse any parts of this however you like. We are currently working towards releasing a comprehensive package for seismo-acoustic processing and beamforming which includes an `Array` object with much more functionality.

For now, feel free to use it as you like.

**Comment by psmsmets** [comment]
Johan is the python consultant for Norsar. :)

**Comment by johanms** [comment]
That's right, should have mentioned I have had contact with @psmsmets.

Thank you, I will use this for now, and I'm looking forward to trying out the new package you are building when the time comes.
